name: Notify Changes

on:
  push:
    branches:
      - main
    paths:
      - 'data/bugcrowd_data.json'
      - 'data/intigriti_data.json'
  workflow_dispatch:  # This allows manual trigger of the workflow

jobs:
  notify_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch bugcrowd_data.json
        id: fetch_bugcrowd_data
        run: |
          curl -o bugcrowd_data.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/bugcrowd_data.json
          cat bugcrowd_data.json  # Debugging output

      - name: Fetch intigriti_data.json
        id: fetch_intigriti_data
        run: |
          curl -o intigriti_data.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/intigriti_data.json
          cat intigriti_data.json  # Debugging output

      - name: Compare files and extract changes
        id: compare_files
        run: |
          echo "Checking previous files..."  # Debugging message
          if [[ -f "previous_bugcrowd_data.json" ]]; then
            diff -u previous_bugcrowd_data.json bugcrowd_data.json > bugcrowd_changes.diff || echo "No changes in bugcrowd_data.json"
          else
            echo "No previous data to compare with"
          fi
          
          if [[ -f "previous_intigriti_data.json" ]]; then
            diff -u previous_intigriti_data.json intigriti_data.json > intigriti_changes.diff || echo "No changes in intigriti_data.json"
          else
            echo "No previous data to compare with"
          fi

      - name: Convert changes to text/plain and send to Discord
        run: |
          changes=""
          if [ -f "bugcrowd_changes.diff" ]; then
            changes=$(cat bugcrowd_changes.diff)
          fi

          if [ -f "intigriti_changes.diff" ]; then
            changes="$changes$(cat intigriti_changes.diff)"
          fi

          echo "Sending changes to Discord..."
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"Changes detected:\n$changes\"}" https://discord.com/api/webhooks/1271818703356297226/RcjQ9wKd27kTNb4vxeaWqmnM4D6y1ltYdu-3CinUcH1I-rtFWKkt2x-Ahz89VZ_u18BD

      - name: Store current files as previous ones for future comparisons
        run: |
          cp bugcrowd_data.json previous_bugcrowd_data.json
          cp intigriti_data.json previous_intigriti_data.json
