name: Sync and Compare Bugcrowd and Intigriti JSONs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Once every hour (adjust as necessary)

jobs:
  sync-and-compare:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the fork repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Add upstream remote (original repository)
      - name: Add upstream remote (only if not already set)
        run: |
          if ! git remote get-url upstream &>/dev/null; then
            git remote add upstream https://github.com/arkadiyt/bounty-targets-data.git
          fi

      # Step 3: Fetch the latest changes from upstream repository
      - name: Fetch the latest changes from upstream
        run: git fetch upstream

      # Step 4: Checkout the `main` branch
      - name: Checkout main branch
        run: git checkout main

      # Step 5: Merge upstream changes into the forked repository
      - name: Merge upstream/main into the forked main
        run: git merge upstream/main --no-edit

      # Step 6: Download the current and previous JSON files from GitHub
      - name: Download current and previous JSON files
        run: |
          curl -s -o current_bugcrowd.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/bugcrowd_data.json
          curl -s -o previous_bugcrowd.json https://raw.githubusercontent.com/rfelecT/bounty-targets-data/main/data/bugcrowd_data.json
          curl -s -o current_intigriti.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/intigriti_data.json
          curl -s -o previous_intigriti.json https://raw.githubusercontent.com/rfelecT/bounty-targets-data/main/data/intigriti_data.json

      # Step 7: Compare JSONs and send to Discord
      - name: Compare JSONs and send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          CHANGES=""

          # Function to compare two JSON files
          compare_jsons () {
            NAME=$1
            FILE1=$2
            FILE2=$3

            DIFF=$(diff -u <(jq -S . "$FILE1") <(jq -S . "$FILE2") || true)
            if [[ -n "$DIFF" ]]; then
              CHANGES+="**${NAME} Changes:**\n\`\`\`\n${DIFF:0:1800}\n\`\`\`\n"
            else
              CHANGES+="✅ No changes in ${NAME}.\n"
            fi
          }

          # Compare Bugcrowd and Intigriti JSON files
          compare_jsons "Bugcrowd" previous_bugcrowd.json current_bugcrowd.json
          compare_jsons "Intigriti" previous_intigriti.json current_intigriti.json

          # If changes are detected, notify Discord
          if [[ "$CHANGES" != *"No changes"* ]]; then
            ESCAPED_CHANGES=$(echo -e "$CHANGES" | sed 's/"/\\"/g')
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\": \"$ESCAPED_CHANGES\"}" \
                 "$DISCORD_WEBHOOK"
          else
            echo "No changes detected."
          fi
