name: Notify Changes

on:
  push:
    branches:
      - main
    paths:
      - 'data/bugcrowd_data.json'
      - 'data/intigriti_data.json'
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  notify_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download current bugcrowd_data.json
        run: |
          curl -o bugcrowd_data.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/bugcrowd_data.json
          cat bugcrowd_data.json  # Debugging step: Print the content of the file

      - name: Download current intigriti_data.json
        run: |
          curl -o intigriti_data.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/intigriti_data.json
          cat intigriti_data.json  # Debugging step: Print the content of the file

      - name: Download previous bugcrowd_data.json (from rfelecT repo)
        run: |
          curl -o previous_bugcrowd_data.json https://raw.githubusercontent.com/rfelecT/bounty-targets-data/main/data/bugcrowd_data.json
          cat previous_bugcrowd_data.json  # Debugging step: Print the content of the file

      - name: Download previous intigriti_data.json (from rfelecT repo)
        run: |
          curl -o previous_intigriti_data.json https://raw.githubusercontent.com/rfelecT/bounty-targets-data/main/data/intigriti_data.json
          cat previous_intigriti_data.json  # Debugging step: Print the content of the file

      - name: Compare and send changes
        run: |
          CHANGES=""

          # Debugging: Check if files are actually downloaded
          echo "Contents of bugcrowd_data.json:"
          cat bugcrowd_data.json
          echo "Contents of previous_bugcrowd_data.json:"
          cat previous_bugcrowd_data.json

          # Compare bugcrowd_data.json
          DIFF_BUGCROWD=$(diff previous_bugcrowd_data.json bugcrowd_data.json)
          if [[ -n "$DIFF_BUGCROWD" ]]; then
            CHANGES="$CHANGES\nBugcrowd Data Changes:\n$DIFF_BUGCROWD"
          else
            CHANGES="$CHANGES\nNo changes detected in bugcrowd_data.json."
          fi

          # Debugging: Check contents of intigriti files
          echo "Contents of intigriti_data.json:"
          cat intigriti_data.json
          echo "Contents of previous_intigriti_data.json:"
          cat previous_intigriti_data.json

          # Compare intigriti_data.json
          DIFF_INTIGRITI=$(diff previous_intigriti_data.json intigriti_data.json)
          if [[ -n "$DIFF_INTIGRITI" ]]; then
            CHANGES="$CHANGES\nIntigriti Data Changes:\n$DIFF_INTIGRITI"
          else
            CHANGES="$CHANGES\nNo changes detected in intigriti_data.json."
          fi

          # Send to Discord if there are changes
          if [[ -n "$CHANGES" ]]; then
            curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"Changes detected:$CHANGES\"}" https://discord.com/api/webhooks/1271818703356297226/RcjQ9wKd27kTNb4vxeaWqmnM4D6y1ltYdu-3CinUcH1I-rtFWKkt2x-Ahz89VZ_u18BD
          else
            echo "No changes detected."
          fi
