name: Check Bugcrowd Target Changes

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq 1.6+
        run: |
          sudo wget -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          sudo chmod +x /usr/bin/jq
          jq --version

      - name: Download latest bugcrowd data
        run: |
          mkdir -p data
          curl -s -o latest.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/refs/heads/main/data/bugcrowd_data.json

      - name: Compare and notify if changed
        run: |
          if [ ! -f data/bugcrowd_data.json ]; then
            echo "No old version found. Saving the latest one."
            cp latest.json data/bugcrowd_data.json
            exit 0
          fi

          added=$(jq '.[].name' latest.json | sort)
          old=$(jq '.[].name' data/bugcrowd_data.json | sort)

          added_list=$(comm -13 <(echo "$old") <(echo "$added"))
          removed_list=$(comm -23 <(echo "$old") <(echo "$added"))

          if [ -z "$added_list" ] && [ -z "$removed_list" ]; then
            echo "No changes detected."
            exit 0
          fi

          message="**Bugcrowd Target Updates**"
          if [ -n "$added_list" ]; then
            message="$message\n\n🟢 **Added:**\n$(echo "$added_list" | sed 's/^/- /')"
          fi
          if [ -n "$removed_list" ]; then
            message="$message\n\n🔴 **Removed:**\n$(echo "$removed_list" | sed 's/^/- /')"
          fi

          # Fix: Properly escape the message to JSON format
          safe_message=$(echo -e "$message" | jq -R .)

          # Send to Discord webhook
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": $safe_message}" \
               "https://discord.com/api/webhooks/1271818703356297226/RcjQ9wKd27kTNb4vxeaWqmnM4D6y1ltYdu-3CinUcH1I-rtFWKkt2x-Ahz89VZ_u18BD"

      - name: Save latest version for next run
        run: cp latest.json data/bugcrowd_data.json

  
