name: Check for Bugcrowd Target Changes

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Download the original bugcrowd_data.json (from arkadiyt)
        run: |
          curl -o original_bugcrowd_data.json "https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/refs/heads/main/data/bugcrowd_data.json"
      - name: Download your modified bugcrowd_data.json (from rfelecT)
        run: |
          curl -o modified_bugcrowd_data.json "https://raw.githubusercontent.com/rfelecT/bounty-targets-data/refs/heads/main/data/bugcrowd_data.json"
      - name: Compare all variables and notify changes
        run: |
          # Loop through all programs and compare each field
          for index in $(jq -r 'keys | .[]' modified_bugcrowd_data.json); do
            original_program=$(jq -r ".[$index]" original_bugcrowd_data.json)
            modified_program=$(jq -r ".[$index]" modified_bugcrowd_data.json)

            # Compare all fields of the program
            if [ "$original_program" != "$modified_program" ]; then
              # If any field is different, extract the URL and notify
              program_url=$(echo "$modified_program" | jq -r '.url')
              echo "Program changed. URL: $program_url"
              
              # Construct the message and send to Discord
              message="Bugcrowd Target Changed:\nURL: $program_url"
              escaped_message=$(echo "$message" | jq -Rs .)

              # Send the message to Discord via the webhook
              curl -H "Content-Type: application/json" \
                   -X POST \
                   -d "{\"content\":$escaped_message}" \
                   "https://discord.com/api/webhooks/1271818703356297226/RcjQ9wKd27kTNb4vxeaWqmnM4D6y1ltYdu-3CinUcH1I-rtFWKkt2x-Ahz89VZ_u18BD"
            fi
          done
