name: Check JSON Changes and Notify

on:
  schedule:
    # Check every 5 minutes (you can adjust this)
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current JSON data
        run: |
          curl -s https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/refs/heads/main/data/intigriti_data.json -o intigriti_data.json
          curl -s https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/refs/heads/main/data/bugcrowd_data.json -o bugcrowd_data.json

      - name: Get old JSON data from rfelecT repository
        run: |
          curl -s https://raw.githubusercontent.com/rfelecT/bounty-targets-data/refs/heads/main/data/intigriti_data.json -o intigriti_data_old.json
          curl -s https://raw.githubusercontent.com/rfelecT/bounty-targets-data/refs/heads/main/data/bugcrowd_data.json -o bugcrowd_data_old.json

      - name: Compare old and new JSON files and set environment variables
        id: compare
        run: |
          DIFF_INTIGRITI=$(diff intigriti_data_old.json intigriti_data.json || echo "No changes")
          DIFF_BUGCROWD=$(diff bugcrowd_data_old.json bugcrowd_data.json || echo "No changes")
          
          # Use jq to format the diff as a JSON string safely
          ESCAPED_DIFF_INTIGRITI=$(echo "$DIFF_INTIGRITI" | jq -R .)
          ESCAPED_DIFF_BUGCROWD=$(echo "$DIFF_BUGCROWD" | jq -R .)
          
          echo "DIFF_INTIGRITI=$ESCAPED_DIFF_INTIGRITI" >> $GITHUB_ENV
          echo "DIFF_BUGCROWD=$ESCAPED_DIFF_BUGCROWD" >> $GITHUB_ENV

      - name: Notify changes
        if: ${{ env.DIFF_INTIGRITI != '"No changes"' || env.DIFF_BUGCROWD != '"No changes"' }}
        run: |
          MESSAGE="Changes detected in the JSON files:\n"
          MESSAGE+="\nIntigriti Data Changes:\n${{ env.DIFF_INTIGRITI }}"
          MESSAGE+="\nBugcrowd Data Changes:\n${{ env.DIFF_BUGCROWD }}"

          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" https://discord.com/api/webhooks/1271818703356297226/RcjQ9wKd27kTNb4vxeaWqmnM4D6y1ltYdu-3CinUcH1I-rtFWKkt2x-Ahz89VZ_u18BD

      - name: Save current JSON files for future comparison
        run: |
          mv intigriti_data.json intigriti_data_old.json
          mv bugcrowd_data.json bugcrowd_data_old.json
