name: Check JSON Changes and Notify

on:
  schedule:
    - cron: '*/5 * * * *'  # Check every 5 minutes (you can adjust this)
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current JSON data
        run: |
          curl -s https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/refs/heads/main/data/intigriti_data.json -o intigriti_data.json
          curl -s https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/refs/heads/main/data/bugcrowd_data.json -o bugcrowd_data.json

      - name: Get previous JSON data (if exists)
        run: |
          if [ -f intigriti_data_old.json ]; then mv intigriti_data_old.json intigriti_data_old.json.bak; fi
          if [ -f bugcrowd_data_old.json ]; then mv bugcrowd_data_old.json bugcrowd_data_old.json.bak; fi

      - name: Compare old and new JSON files
        id: compare
        run: |
          if [ -f intigriti_data_old.json ]; then
            diff intigriti_data_old.json.bak intigriti_data.json || echo "Changes detected in intigriti_data.json"
          fi
          if [ -f bugcrowd_data_old.json ]; then
            diff bugcrowd_data_old.json.bak bugcrowd_data.json || echo "Changes detected in bugcrowd_data.json"
          fi

      - name: Notify changes
        if: steps.compare.outcome == 'failure'
        run: |
          DIFF_INTIGRITI=$(diff intigriti_data_old.json.bak intigriti_data.json || echo "No changes")
          DIFF_BUGCROWD=$(diff bugcrowd_data_old.json.bak bugcrowd_data.json || echo "No changes")
          
          MESSAGE="Changes detected in the JSON files:\n"
          MESSAGE+="\nIntigriti Data Changes:\n$DIFF_INTIGRITI"
          MESSAGE+="\nBugcrowd Data Changes:\n$DIFF_BUGCROWD"

          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" https://discord.com/api/webhooks/1271818703356297226/RcjQ9wKd27kTNb4vxeaWqmnM4D6y1ltYdu-3CinUcH1I-rtFWKkt2x-Ahz89VZ_u18BD
      - name: Save current JSON files for future comparison
        run: |
          mv intigriti_data.json intigriti_data_old.json
          mv bugcrowd_data.json bugcrowd_data_old.json
