name: Compare JSONs and Notify Discord

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour; change as needed

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Download current bugcrowd_data.json
        run: curl -s -o current_bugcrowd.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/bugcrowd_data.json

      - name: Download previous bugcrowd_data.json
        run: curl -s -o previous_bugcrowd.json https://raw.githubusercontent.com/rfelecT/bounty-targets-data/main/data/bugcrowd_data.json

      - name: Download current intigriti_data.json
        run: curl -s -o current_intigriti.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/intigriti_data.json

      - name: Download previous intigriti_data.json
        run: curl -s -o previous_intigriti.json https://raw.githubusercontent.com/rfelecT/bounty-targets-data/main/data/intigriti_data.json

      - name: Compare JSON files and send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          CHANGES=""

          DIFF_BUGCROWD=$(diff -u previous_bugcrowd.json current_bugcrowd.json || true)
          if [[ -n "$DIFF_BUGCROWD" ]]; then
            CHANGES+="**Bugcrowd Changes:**\n\`\`\`\n${DIFF_BUGCROWD:0:1800}\n\`\`\`\n"
          else
            CHANGES+="No changes in bugcrowd_data.json.\n"
          fi

          DIFF_INTIGRITI=$(diff -u previous_intigriti.json current_intigriti.json || true)
          if [[ -n "$DIFF_INTIGRITI" ]]; then
            CHANGES+="**Intigriti Changes:**\n\`\`\`\n${DIFF_INTIGRITI:0:1800}\n\`\`\`\n"
          else
            CHANGES+="No changes in intigriti_data.json.\n"
          fi

          if [[ -n "$CHANGES" ]]; then
            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"$CHANGES\"}" \
              "$DISCORD_WEBHOOK_URL"
          fi
