Run CHANGES=""
  CHANGES=""
  
  compare_jsons () {
    NAME=$1
    FILE1=$2
    FILE2=$3
  
    DIFF=$(diff -u <(jq -S . "$FILE1") <(jq -S . "$FILE2") || true)
    if [[ -n "$DIFF" ]]; then
      CHANGES+="**${NAME} Changes:**\n\`\`\`\n${DIFF:0:1800}\n\`\`\`\n"
    else
      CHANGES+="✅ No changes in ${NAME}.\n"
    fi
  }
  
  compare_jsons "Bugcrowd" previous_bugcrowd.json current_bugcrowd.json
  compare_jsons "Intigriti" previous_intigriti.json current_intigriti.json
  
  if [[ "$CHANGES" != *"No changes"* ]]; then
    ESCAPED_CHANGES=$(echo -e "$CHANGES" | sed 's/"/\\"/g')
    curl -H "Content-Type: application/json" \
         -X POST \
         -d "{\"content\": \"$ESCAPED_CHANGES\"}" \
         "$DISCORD_WEBHOOK"
  else
    echo "No changes detected."
  fi
  shell: /usr/bin/bash -e {0}
  env:
    DISCORD_WEBHOOK: ***
No changes detected.
