name: Check Bugcrowd Target Changes

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq 1.6+
        run: |
          sudo wget -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          sudo chmod +x /usr/bin/jq
          jq --version

      - name: Download latest bugcrowd data
        run: |
          mkdir -p data
          curl -s -o latest.json https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/refs/heads/main/data/bugcrowd_data.json

      - name: Compare and notify if changed
        run: |
          if [ ! -f data/bugcrowd_data.json ]; then
            echo "No old version found. Saving the latest one."
            cp latest.json data/bugcrowd_data.json
            exit 0
          fi

          added=$(jq -n --argfile old data/bugcrowd_data.json --argfile new latest.json \
            '($new - $old) | map(.name)')

          removed=$(jq -n --argfile old data/bugcrowd_data.json --argfile new latest.json \
            '($old - $new) | map(.name)')

          added_count=$(echo "$added" | jq 'length')
          removed_count=$(echo "$removed" | jq 'length')

          if [ "$added_count" -eq 0 ] && [ "$removed_count" -eq 0 ]; then
            echo "No changes detected."
            exit 0
          fi

          message="**Bug**
